version: '3'
services:
        web:
                ports:
                 - "3000:3000"
                volumes:
                 - /app/node_volumes
                 - .:/app
                build: 
                        context: .
                        dockerfile: dockerfile.dev
